In [1]:
import numpy as np

# Instructions de flot de contrôle:
# - Sequence: retour à la ligne
# - Branchement: if: // elif: // else: //
# - No-op: pass
# - Boucle for: for i in range(start, stop, step): //
# - Boucle while: while cond: //
# - Sortie boucle: break
# - Itération suivante: continue


# Liste des valeurs définies en mini-python
from numpy import Infinity

# Liste des fonctions définies en mini-python
min, max
from numpy import sqrt
from numpy import floor
from numpy import abs
from numpy import exp, log
from numpy import sin, cos, tan
from numpy import arcsin, arccos, arctan
from numpy import sinh, cosh, tanh
from numpy import arcsinh, arccosh, arctanh
from numpy import mod

def size(t):
    shape = np.shape(t)
    if np.ndim(t) == 1:
        return shape[0]
    else:
        return shape

def rand():
    return np.random.random()

def vector(n):
    if np.isscalar(n):
        return np.zeros(n)
    else:
        return np.array(n)
    
def matrix(n, m):
    return np.zeros((n, m))

def tensor(*args):
    return np.zeros(args)

def array(a):
    return np.array(a)

def length(s):
    return len(s)

def substr(s, begin, length):
    return s[begin:begin+length]

# Les instructions de contrôle

## Boucles à compteur

```python
for i in range(start, stop, step):
    pass
```

À une itération `n`, `i` vaut :
$$
\begin{align}
\mathsf{i}_0 & = \mathsf{start} \\
\mathsf{i}_n & = \mathsf{i}_{n-1} + \mathsf{step} &
\forall{n}\in\mathbb{N}^{*}
\end{align}
$$

- Si $\mathsf{step} > 0$, on a pour toute itération
$\mathsf{start} \leq \mathsf{i} < \mathsf{stop}$.
- Si $\mathsf{step} < 0$, on a pour toute itération
$\mathsf{stop} < \mathsf{i} \leq \mathsf{start}$.

**Exemple** : Calcul de la factorielle de $n$:

In [2]:
N = 3

# Factorielle
res = 1
for i in range(1, N + 1, 1): # i ∈ [1, N]
    res = i * res

res

6

**Exemple** : Calcul de la somme des éléments d’indices pairs et impairs d’un tableau `t` de taille $N$.

In [3]:
T = [1, 2, 3, 4]
N = size(T)

# Calcul éléments pairs et impairs
impair = 0
pair = 0

for i in range(1, N, 2):
    impair = impair + T[i]
    
for i in range(0, N, 2):
    pair = pair + T[i]

impair, pair

(6, 4)

**Exemple** : Tri dans l’ordre croissant des éléments d’un vecteur V

In [4]:
V = [4, 5, 3, 1]
N = size(V)

# Tri dans l'ordre croissant de V
for i in range(0, N-1, 1): # i ∈ [1, N-2]
    for j in range(i+1, N):
        # On compare le V[i] courant avec toutes les indices suivant i
        if (V[i] < V[j]):
            # On échange V[i] et V[j] si V[i] < V[j] 
            tmp = V[i]
            V[i] = V[j]
            V[j] = tmp

V

[5, 4, 3, 1]

**Exemple** : recherche du minimum dans un vecteur `V`

In [5]:
V = [2, 3, 4, 5, 6]
N = size(V)

# Recherche de la valeur minimale de v
mn = +Infinity
for i in range(0, N, 1):
    if V[i] < mn:
        mn = V[i]

mn

2

**Exemple** : *Tri par sélection*

On combine l'algo de tri ci-dessus avec l'algo de recherche de minimum

In [6]:
V = [4, 5, 3, 1]
N = size(V)

for i in range(0, N-1, 1):
    mn = V[i]
    idx = i
    # Recherche de l'élément minimal
    for j in range(i+1, N, 1):
        if (V[j] < mn):
            mn = V[j]
            idx = j
    # On échange la valeur à l'indice courant avec l'élement minimal
    G = V[idx]
    V[idx] = V[i]
    V[i] = G

V

[1, 3, 4, 5]

### Exercice 1.9

Algorithme retournant, pour un entier N donné, la valeur au rang N de la suite de Fibonnaci $(\mathcal{F}_n)_{n\in\mathbb{N}}$

In [7]:
N = 12

In [8]:
# Solution 1

F0 = 1
F1 = 1

for i in range(2, N, 1):
    F2 = F0 + F1
    F0 = F1
    F1 = F2
    
F1

144

In [9]:
# Solution 2

F0 = 1
F1 = 1

for i in range(2, N, 1):
    F1 = F0 + F1
    F0 = F1 - F0
    
F1

144

## Les boucles tant que

```python
while cond:
    pass
```

On itère tant que la condition `cond` est vérifiée.

### Exemple : Méthode du Héron

In [10]:
A = 16
EPSILON = 10 ** (-16)

# Méthode du héron
r = 1
tmp = 0

while abs(tmp - r) >= EPSILON:
    tmp = r
    r = (r + A /  r) / 2

r

4.0

### Exercice 1.10

Algorithme retournant le nombre d'itération de la suite de Syracuse pour un entier initial $N\in\mathbb{N}^{*}$

In [11]:
N = 4000

U = N # u_0 = N
I = 0 # Nombre d'itérations

while U != 1:
    I = I + 1
    if U % 2 == 0:
        U = U/2   # u_(n+1) = u_(n) / 2
    else:
        U = 3*U+1 # u_(n+1) = 3*(u_(n)) + 1

U, I

(1.0, 113)

### Boucles jusqu'à ce que

Il n'y a pas de boucles "do-until" en python (et par extension en mini-python). L'idée étant que l'on ne boucle plus si la condition est remplie en fin d'itération !

### Exercice 1.11

## Sorties de boucle

```python
while True:      # [0]
    # ...        # [1]
    break        # [2]
    # ...        # [3]

# ...            # [4]
```

Ordre d'exécution:
$$
[0] \rightarrow [1] \rightarrow [2] \rightarrow [4]
$$

**Exemple** : calcul de plus petite valeur de n tel que la somme des $n$ dépasse $10000$

In [12]:
s = 0
n = 1

while True:
    s = s + n * n
    n = n + 1
    if s > 10000:
        break

n

32

**Exemple** : recherche d’un élément E dans un tableau

In [13]:
T = [1, 2, 3, 4, 5, 6, 7]
E = 4

# Recherche de E dans T
n = size(T)
present = False

for i in range(0, n):
    if T[i] == E:
        present = True

present

True

## Passage à l'itération suivante

```python
while True:      # [0]
    # ...        # [1]
    continue     # [2]
    # ...        # [3]

# ...            # [4]
```

Ordre d'exécution:
$$
[0] \rightarrow [1] \rightarrow [2] \rightarrow [1] \rightarrow [2]
\rightarrow \dots
$$

**Exemple** : recherche de l'élément maximal d'un vecteur

In [14]:
T = [1, 2, 3, 4, 5, 6, 7]

# Recherche de l'indice de l'élement max
n = size(T)
m = -Infinity
idx = 0
for i in range(0, n, 1):
    if T[i] < m:
        continue
    m = T[i]
    idx = i
    
idx

6

## Goto

- Sauter à n'importe quelle instruction du programme.
- Edsger Dijkstra: *Go To Statement Considered Harmful*

### Exercice 1.14 : Expressivité de `goto`

# Profondeur de code

**Squelette d'un algorithme** : Structure du code, soit l'ensemble des instructions de contrôle (disjonctions, boucles, sorties de boucles et passage à l'itération suivante).

```python
for:
    for:
        for:
            if:
                continue
```

**Degré d'emboitement** : Nombre maximal de boucles et disjonctions imbriquées. Généralement en python, le degré d'emboitement est donné par le nombre de tabulation maximal de votre code.

### Exercice 1.15

1. Ecrire un algorithme permettant de générer automatiquement une matrice aléatoire de dimension $N \times M$ dont les éléments sont des entiers tirés suivant une loi uniforme définie sur l’intervalle $[1, 100]$.

In [15]:
# Comment générer un nombre aléatoire entre [1, 100] ?

floor(100 * rand()) + 1

48.0

In [16]:
N = 4
M = 5

# Génération de la matrix N*M
T = matrix(N, M)

for i in range(0, N, 1):
    for j in range(0, M, 1):
        T[i][j] = floor(100 * rand()) + 1

T

array([[63., 46., 87., 45., 90.],
       [61., 50., 90., 48., 15.],
       [17.,  5., 20., 54., 73.],
       [20., 80., 55.,  8., 17.]])

2. Compléter cet algorithme avec les instructions permettant de rechercher dans la matrice générée, la plus longue séquence de nombres entiers (une séquence étant définie comme une suite d’entiers consécutifs sur une ligne ou une colonne donnée). L’algorithme devra retourner la longueur de cette séquence. Notons que cette longueur ne peut excéder `max(N, M, 100)`.

In [17]:
MAX_EN_LIGNE = 0

for i in range(0, N, 1):
    seq = 1
    for j in range(1, M-1, 1):
        # tant que consécutif, on incrémente seq
        if T[i][j+1] - T[i][j] == 1:
            seq = seq + 1
        # si non
        else:
            seq = 1
    
# TODO: Matrice transposée

3. Ecrire le squelette de l’algorithme et indiquer son degré d’emboîtement.

# Les modules/functions

In [18]:
def identificateur_de_module(p1, p2, p3, pn): # paramètres formels
    pass # Corps du module

# appel du module avec des paramètres actuels
identificateur_de_module(1, 2.0, "p3", [4, 5])

**Passage par référence et par valeur**


**Cas de python et mini-python**

In [19]:
# Génère une matrice aléatoire de dimension n * m
# où l'ensemble de ces éléments sont compris dans [min, max[
def random_int_matrix(n, m, min, max):
    mat = matrix(n, m)
    for i in range(0, n, 1):
        for j in range(0, m, 1):
            v = floor(rand() * abs(max - min)) + min
            mat[i][j] = v
    return mat

random_int_matrix(4, 4, 0, 2)

array([[1., 1., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.]])

**Exemple**: Modularisation d'un code de produit matriciel

In [20]:
N = 2

A = random_int_matrix(N, N, 0, 4)
B = random_int_matrix(N, N, 0, 4)
C = random_int_matrix(N, N, 0, 4)

def multiply_matrices(a, b, c):
    # Récupération des tailles des matrices
    sa = size(A)
    sb = size(B)
    nla = sa[0]
    nca = sa[1]
    ncb = sb[1]
    # Calcul du produit matriciel
    for i in range(0, nla, 1):
        for j in range(0, ncb, 1):
            c[i, j] = 0
            for k in range(0, nca, 1):
                c[i, j] = c[i, j] + a[i, k] * b[k, j]
                
multiply_matrices(A, B, C)

A, B, C
# np.dot(A, B)

(array([[3., 1.],
        [3., 1.]]),
 array([[1., 3.],
        [0., 3.]]),
 array([[ 3., 12.],
        [ 3., 12.]]))

## Débranchement/Sortie de module

In [21]:
def function():
    print(1) # [1]
    return
    print(2) # [2]

print('0')
function()
print('3')

0
1
3


In [22]:
# TODO

**Exemple**: écrivons un algorithme de transposition de matrice (nous supposerons ici que la matrice à transposer est carrée)

In [23]:
# Transposée en place
def transpose(A):
    S = size(A)
    NL = S[0]
    for i in range(0, NL, 1):
        for j in range(0, i):
            G = A[i, j]
            A[i, j] = A[j, i]
            A[j, i] = G


# Transposée en copie
# => Itération sur tous les indices et copie dans une nouvelle matrice

In [24]:
A = random_int_matrix(3, 3, 0, 5)

print(A)

transpose(A)
print(A)

[[3. 0. 0.]
 [0. 4. 1.]
 [3. 1. 2.]]
[[3. 0. 3.]
 [0. 4. 1.]
 [0. 1. 2.]]


**Attention** : nous conclurons cette partie en indiquant que si les paramètres formels d’un module sont nécessairement des identificateurs (de quelque type que ce soit), il n’en va pas de même pour les paramètres actuels qui peuvent être :
- des constantes
- des identificateurs auxquels on aura préalablement affecté une variable
- des expressions algébriques (à valeur dans l’ensemble spécifié par le paramètre formel correspondant).

## Types de modules

- Fonction vs Procédures

On étend la syntaxe précédente avec `return` d'une valeur
```py
def function():
    return 42
    
x = function() # x vaut 42
```


**Exemple 1** Norme d'un vecteur

In [25]:
def norm(V):    # V ici n'est passé qu'en entrée
    T = size(V)
    NORM = 0
    for i in range(0, T, 1):
        NORM = NORM + V[i] * V[i]
    return sqrt(NORM)

V = np.array([1, 2, 4])
norm(V)

4.58257569495584

**Exemple 2** Normalisation d'un vecteur

In [26]:
V = np.array([1.0, 2.0, 4.0])

def normalize(V): # V est passé en entrée et en sortie
    T = size(V)
    N = norm(V)
    if N == 0:
        return
    for i in range(0, T, 1):
        V[i] = V[i] / N

normalize(V)
V

array([0.21821789, 0.43643578, 0.87287156])

### Exercice 1.17

In [27]:
def sparse(v, e):
    t = size(v)
    n = 0
    for i in range(0, t, 1):
        if abs(v[i] <= e):
            V[i] = 0
            n = n + 1
    return n

V = [1, 2, 3, 4]
sparse(V, 2), V

(2, [0, 0, 3, 4])

### Exercice 1.18. Matrice creuse

Pour une matrice de taille carrée de taill $n\times{n}$, il
faut garder en mémoire $n*m$ nombres.
Dans la représentation creuse, il faut garder en mémoire pour chaque entrée 3 nombres (2 indices $i$ et $j$ ainsi que l'élément `M[i, j] != 0`).

Soit $p$ le nombre d'élements non-nuls. La représentation en matrice
creuse est alors avantageuse si et seulement si $3p\leq nm$, d'où
$p \leq \frac{nm}{3}$.
   
La représentation matricielle est avantageuse dès lors que plus des
deux tiers des éléments de la matrice sont nuls.

In [28]:
def matrix_creuse(m, c):
    s = size(m)
    t = 0
    for i in range(0, s[0], 1):
        for j in range(0, s[1], 1):
            if m[i, j] != 0:
                t = t + 1
                c[t, 0] = i
                c[t, 1] = j
                c[r, 2] = m[i, j]
    return s[0] * s[1] / (3 * t)

## Modules recursifs

Un module (fonction ou procédure) est dit **récursif**, dès lors que son corps de module comprend au moins un appel à lui-même.

```py
def mod_rec(p1, p2, ..., pn):
    pass
    mod_rec(a1, a2, ..., an)
    pass
```

In [29]:
# Calcul de la factorielle
def factorial(n):
    if (n <= 1):
        return 1
    return n * factorial(n - 1)

In [30]:
# Exponentiation
def expn(x, n):
    if n == 0:
        return 1
    return x * expn(x, n - 1)

**Note**: un module récursif peut faire appel à lui-même plus d’une fois dans son corps de module.

In [31]:
# Exponentiation rapide
def fast_expn(x, n):
    if n == 0:
        return 1
    if n % 2 == 0:
        return fast_expn(x, n / 2) * fast_expn(x, n / 2)
    else:
        return fast_expn(x, n // 2) * fast_expn(x, n // 2) * x
    
# Attention à la division d'indices entiers !

In [32]:
# Exponentiation rapide (optimisée)
def fast_expn_v2(x, n):
    if n == 0:
        return 1
    r = fast_expn_v2(x, n // 2)
    r = r * r
    if (n % 2 != 0):
        r = x * r
    return r

In [33]:
# En appelant les fonctions précédentes

x = 2
n = 10

x**n, expn(x, n), fast_expn(x, n), fast_expn_v2(x, n)

(1024, 1024, 1024, 1024)

In [34]:
# Suite de Fibonnaci
def fibo(n):
    if n <= 2:
        return 1
    return fibo(n - 1) + fibo(n - 2)

In [35]:
fibo(2), fibo(3), fibo(4), fibo(5)

(1, 2, 3, 5)

### Exemple 5 : le tri fusion

In [36]:
# TODO: Algo en python

def fusion(t1, t2, t):
    n1 = size(t1)
    n2 = size(t2)
    i1 = 1
    i2 = 1
    while i1 <= n1 and i2 <= n2:
        i = i1 + i2 - 1
        if t1[i1] <= t2[i2]:
            t[i] = t1[i1]
            i1 = i1 + 1
        else:
            t[i] = t2[i2]
            i2 = i2 + 1
            
def trifusion(t):
    n = size(t)
    if n <= 1:
        return t
    
# TODO

### Exercice 1.20: Écrire une version récursive du module `fusion`

### Exercide 1.21: Recherche d'un élément dans une liste

### Recursivité croisée

On parle de récursivité croisée, lorsque deux fonctions s’appellent mutuellement.

### Exercice 1.23 : Pair et impair

# Chaînes de caractères

Deux fonctions de manipulation :
- `length(s)`:
  + entrée: une *chaine de caractère* `s`
  + sortie: la taille de `s` (en nombre de caractères).
- `substr(s, i, l)`:
  + entrée: une *chaine de caractères* `s`, un indice initial `i` et
    une longueur `l`.
  + sortie: la sous-chaine de `s` de longueur `l` débutant à `i`

In [37]:
s = "voici un exemple"
length(s), substr(s, 9, 7)

(16, 'exemple')

# Exercices

Pour chacun des algoritmes ci-dessous, lorsqu'il est demandé d'écrire un algorithme, on donnera le code `mini-Python`, le squelette ainsi que le degré d'emboitement.

### Exercice 1.24 : Demi-additionneur logique

1. Le premier circuit est écrit en algèbre booléenne par :
   $$
   \begin{align}
   S &= \overline{(A + B)} \\
   C &= AB
   \end{align}
   $$

   Le second circuit est écrit en alèbre booléenne par :
   $$
   \begin{align}
   S &= \overline{%
     \overline{A\overline{AB}}\ \overline{B\overline{AB}}
   }
   \\
   C &= \overline{1\overline{(AB)}}
   \end{align}
   $$
   

2. Toute logique peut-être exprimée seulement par `nand` (i.e $\overline{ab}$) :
   $$
   \begin{align}
   \overline{a} &= \overline{aa} & \text{non}\\
   ab &= \overline{\overline{ab}} & \text{and}\\
   a + b &= \overline{\overline{a}\overline{b}} & \text{or}\\
   a\overline{b} + \overline{a}b & & \text{xor}
   \end{align}
   $$
   
  Idem pour l'opérateur logique `nor` (je vous laisse faire le même exercice si ça vous amuse).

### Exercice 1.25 : Miroir d'une chaîne de caractère

In [38]:
def reverse_string(s):
    rev = ""
    n = length(s)
    for i in range(n, -1, -1):
        rev = rev + substr(s, i, 1)
    return rev

In [39]:
reverse_string('programme'), reverse_string('kayak')

('emmargorp', 'kayak')

### Exercice 1.26 : Décompte de mots

In [40]:
def word_count(s):
    if s == "":
        return 0
    count = 1
    n = length(s)
    for i in range(0, n, 1):
        if substr(s, i, 1) == " ":
            count = count + 1
    return count

word_count("un leger matin d'été")

# L'algo ci-dessus pourrait être plus intelligent
# i.e reconnaitre les espaces multiples

4

### Exercice 1.27 : Calcul de $\pi$ par Monte-Carlo

In [41]:
def pi_monte_carlo(N, xc, yc, r, xmin, ymin, xmax, ymax):
    n = 0
    print(xmin, xmax)
    print(ymin, ymax)
    for i in range(0, N, 1):
        # [xmin, xmax] = [0, xmax - xmin] - [xmin, xmin]
        #              = ([0, 1] - xmin) / (xmax - xmin)
        x = rand() * (xmax - xmin) + xmin
        y = rand() * (ymax - ymin) + ymin
        # distance à l'origine
        d = sqrt((x - xc) ** 2 + (y - yc) ** 2)
        if d <= r:
            n = n + 1
    aire_emprise = (xmax - xmin) * (ymax - ymin)
    aire_cercle = n / N * aire_emprise
    return aire_cercle / r ** 2

pi_monte_carlo(100000, 0, 0, 2, -2, -2, 2, 2)
        
# TODO: Plot pour que ce soit plus visuel

-2 2
-2 2


3.14896

### Exercice 1.28 : Analyse des fréquences dans une chaine de caractères

### Exercice 1.29 : Ligne de somme maximale dans une matrice

### Exercice 1.30 : Logarithme itéré $\log^{*}_{b} x$

In [42]:
def log_iter(b, x):
    if x <= 1:
        return 1
    return 1 + log_iter(log(x)/log(b), b)

log_iter(2, 64)

4

### Exercice 1.31 : Recherche dichotomique

In [43]:
# Version recursive
def binary_search(arr, x, low, up):
    if up < low:
        return False
    mid = (low + up) // 2 
    if x == arr[mid]:
        return True
    elif x > arr[mid]:
        return binary_search(arr, x, mid + 1, up)
    else:
        return binary_search(arr, x, low, mid - 1)

# Version itérative
def binary_search_iter(a, x, low, up):
    while low <= up:
        mid = (up + low) // 2
        if a[mid] == x:
            return True
        elif a[mid] < x:
            low = mid + 1
        else:
            up = mid - 1
    return False

In [44]:
def search_rec(a, x):
    return binary_search(a, x, 0, len(a) - 1)

def search_iter(a, x):
    return binary_search_iter(a, x, 0, len(a) - 1)

### Exercice 1.34 : Multiplication de grands entiers

In [45]:
def mult_bigint(a, b):
    na = size(a)
    nb = size(b)
    s = 0
    for i in range(0, na, 1):
        for j in range(0, nb, 1):
            x = a[i] * (10 ** (na - i - 1))
            y = b[j] * (10 ** (nb - j - 1))
            s = s + x * y
    return s

### Exercice 1.36: Problèmes de satisfiabilité

TODO: Poly correction sur papier